engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
    channel: "eslint-3"
    config:
        config: .eslintrc
    checks:
        import/no-unresolved:
          enabled: false
  fixme:
    enabled: true
ratings:
  paths:
  - "**.js"
exclude_paths:
